version: '3.8'

services:
  db:
    image: postgis/postgis:16-3.4
    container_name: bhuveda_postgis
    environment:
      POSTGRES_DB: bhuveda_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: bhuveda_backend
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:postgrespassword@db:5432/bhuveda_db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: bhuveda_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  pgdata:
